# Generated by Django 2.2.7 on 2019-12-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(unique=True)),
                ('date', models.TextField()),
                ('nums_1', models.IntegerField()),
                ('nums_2', models.IntegerField()),
                ('nums_3', models.IntegerField()),
                ('nums_4', models.IntegerField()),
                ('nums_5', models.IntegerField()),
                ('nums_6', models.IntegerField()),
                ('nums_bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WinningData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('total_money', models.TextField()),
                ('winner', models.TextField()),
                ('each_money', models.TextField()),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.Lotto')),
            ],
            options={
                'unique_together': {('count', 'rank')},
            },
        ),
    ]
